import type { Client, Driver, Delivery } from "./types";

export const CLIENTS: Client[] = [
  { id: "c1", name: "Cascade Foods" },
  { id: "c2", name: "Harbor Market" },
  { id: "c3", name: "Summit Ridge" },
  { id: "c4", name: "Northline Bakery" },
];

export const DRIVERS: Driver[] = [
  { id: "d1", name: "Marcus T.", vehicle: "Pickup Truck", isActive: true },
  { id: "d2", name: "Priya K.",  vehicle: "Cargo Van",   isActive: true },
  { id: "d3", name: "Devon H.", vehicle: "Box Truck",    isActive: true },
  { id: "d4", name: "Sasha L.", vehicle: "Cargo Van",    isActive: true },
];

export const VEHICLE_TYPES = [
  "Motorcycle",
  "Sedan / Car",
  "Pickup Truck",
  "SUV",
  "Cargo Van",
  "Box Truck",
  "Wing Van",
  "6-Wheeler Truck",
  "10-Wheeler Truck",
] as const;

const today = new Date().toISOString().slice(0, 10);

export const DELIVERIES: Delivery[] = [
  {
    id: "SR-0081",
    date: today,
    clientId: "c1",
    status: "open",
    srProblemSummary: "Defective refrigeration units for pullout and replacement",
    declaredQuantity: 4,
    customerName: "Green Valley Superstore",
    contactAddressLine1: "412 Westlake Ave N",
    contactAddressLine2: "Seattle, WA 98109",
    proposedPulloutSchedule: `${today}T08:00`,
    actualDateOfPullout: null,
    vehicleType: "Box Truck",
    driverId: null,
    actualQuantity: null,
    dispatchNotes: "Leave at loading dock B",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "SR-0082",
    date: today,
    clientId: "c2",
    status: "claimed",
    srProblemSummary: "Expired stock removal — canned goods aisle",
    declaredQuantity: 12,
    customerName: "Jon Marsh / Harbor Central",
    contactAddressLine1: "1521 Pike Place",
    contactAddressLine2: "Seattle, WA 98101",
    proposedPulloutSchedule: `${today}T09:00`,
    actualDateOfPullout: null,
    vehicleType: "Cargo Van",
    driverId: "d1",
    actualQuantity: null,
    dispatchNotes: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "SR-0083",
    date: today,
    clientId: "c3",
    status: "picked_up",
    srProblemSummary: "Broken display shelving — fragile glassware",
    declaredQuantity: 6,
    customerName: "Ana Rivera",
    contactAddressLine1: "220 2nd Ave Ext S",
    contactAddressLine2: "Seattle, WA 98104",
    proposedPulloutSchedule: `${today}T10:00`,
    actualDateOfPullout: null,
    vehicleType: "Pickup Truck",
    driverId: "d2",
    actualQuantity: null,
    dispatchNotes: "Fragile — handle with care",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "SR-0084",
    date: today,
    clientId: "c4",
    status: "delivered",
    srProblemSummary: "Faulty chiller compressor removal",
    declaredQuantity: 1,
    customerName: "Northline Central Branch",
    contactAddressLine1: "6801 Roosevelt Way NE",
    contactAddressLine2: "Seattle, WA 98115",
    proposedPulloutSchedule: `${today}T07:30`,
    actualDateOfPullout: today,
    vehicleType: "Box Truck",
    driverId: "d3",
    actualQuantity: 1,
    dispatchNotes: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "SR-0085",
    date: today,
    clientId: "c1",
    status: "completed",
    srProblemSummary: "Recalled product batch — dry goods",
    declaredQuantity: 30,
    customerName: "Cascade Main Warehouse",
    contactAddressLine1: "1000 1st Ave",
    contactAddressLine2: "Seattle, WA 98104",
    proposedPulloutSchedule: `${today}T06:00`,
    actualDateOfPullout: today,
    vehicleType: "Wing Van",
    driverId: "d4",
    actualQuantity: 28,
    dispatchNotes: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "SR-0086",
    date: today,
    clientId: "c2",
    status: "open",
    srProblemSummary: "Damaged packaging — beverage pallet",
    declaredQuantity: 8,
    customerName: "Harbor North Outlet",
    contactAddressLine1: "4500 9th Ave NE",
    contactAddressLine2: "Seattle, WA 98105",
    proposedPulloutSchedule: `${today}T13:00`,
    actualDateOfPullout: null,
    vehicleType: "Cargo Van",
    driverId: null,
    actualQuantity: null,
    dispatchNotes: "Call ahead 30 min",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "SR-0087",
    date: today,
    clientId: "c3",
    status: "open",
    srProblemSummary: "Overstock return — seasonal items",
    declaredQuantity: 20,
    customerName: "Summit Fremont Store",
    contactAddressLine1: "3601 Fremont Ave N",
    contactAddressLine2: "Seattle, WA 98103",
    proposedPulloutSchedule: `${today}T11:00`,
    actualDateOfPullout: null,
    vehicleType: "6-Wheeler Truck",
    driverId: null,
    actualQuantity: null,
    dispatchNotes: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "SR-0088",
    date: today,
    clientId: "c4",
    status: "claimed",
    srProblemSummary: "Safety recall — electrical appliances",
    declaredQuantity: 15,
    customerName: "Eli Tran / Rainier Branch",
    contactAddressLine1: "9020 Rainier Ave S",
    contactAddressLine2: "Seattle, WA 98118",
    proposedPulloutSchedule: `${today}T14:00`,
    actualDateOfPullout: null,
    vehicleType: "Box Truck",
    driverId: "d2",
    actualQuantity: null,
    dispatchNotes: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

let _srSeq = 89;
export function nextOrderId(): string {
  return `SR-${String(_srSeq++).padStart(4, "0")}`;
}
