import type { Client, Driver, Delivery } from "./types";

export const CLIENTS: Client[] = [
  { id: "c1", name: "Cascade Foods" },
  { id: "c2", name: "Harbor Market" },
  { id: "c3", name: "Summit Ridge" },
  { id: "c4", name: "Northline Bakery" },
];

export const DRIVERS: Driver[] = [
  { id: "d1", name: "Marcus T.", vehicle: "Ford Transit", isActive: true },
  { id: "d2", name: "Priya K.", vehicle: "Sprinter Van", isActive: true },
  { id: "d3", name: "Devon H.", vehicle: "Cargo Bike", isActive: true },
  { id: "d4", name: "Sasha L.", vehicle: "Tesla Model 3", isActive: true },
];

export const DELIVERIES: Delivery[] = [
  {
    id: "RL-0081",
    clientId: "c1",
    status: "open",
    address: "412 Westlake Ave N, Seattle, WA 98109",
    timeWindowStart: "08:00",
    timeWindowEnd: "10:00",
    driverId: null,
    contactName: null,
    contactPhone: null,
    deliveryNotes: null,
    dispatchNotes: "Leave at loading dock B",
    lat: 47.6335,
    lng: -122.336,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "RL-0082",
    clientId: "c2",
    status: "claimed",
    address: "1521 Pike Place, Seattle, WA 98101",
    timeWindowStart: "09:00",
    timeWindowEnd: "11:30",
    driverId: "d1",
    contactName: "Jon Marsh",
    contactPhone: "206-555-0142",
    deliveryNotes: "Ring buzzer twice",
    dispatchNotes: null,
    lat: 47.6097,
    lng: -122.3422,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "RL-0083",
    clientId: "c3",
    status: "picked_up",
    address: "220 2nd Ave Ext S, Seattle, WA 98104",
    timeWindowStart: "10:00",
    timeWindowEnd: "12:00",
    driverId: "d2",
    contactName: "Ana Rivera",
    contactPhone: "206-555-0198",
    deliveryNotes: null,
    dispatchNotes: "Fragile — glassware",
    lat: 47.5996,
    lng: -122.3313,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "RL-0084",
    clientId: "c4",
    status: "delivered",
    address: "6801 Roosevelt Way NE, Seattle, WA 98115",
    timeWindowStart: "07:30",
    timeWindowEnd: "09:00",
    driverId: "d3",
    contactName: null,
    contactPhone: null,
    deliveryNotes: "Place in cooler room",
    dispatchNotes: null,
    lat: 47.6824,
    lng: -122.3185,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "RL-0085",
    clientId: "c1",
    status: "completed",
    address: "1000 1st Ave, Seattle, WA 98104",
    timeWindowStart: "06:00",
    timeWindowEnd: "08:00",
    driverId: "d4",
    contactName: "Beam Logistics",
    contactPhone: "206-555-0011",
    deliveryNotes: null,
    dispatchNotes: null,
    lat: 47.6039,
    lng: -122.3359,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "RL-0086",
    clientId: "c2",
    status: "open",
    address: "4500 9th Ave NE, Seattle, WA 98105",
    timeWindowStart: "13:00",
    timeWindowEnd: "15:00",
    driverId: null,
    contactName: null,
    contactPhone: null,
    deliveryNotes: null,
    dispatchNotes: "Call ahead 30 min",
    lat: 47.6602,
    lng: -122.3136,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "RL-0087",
    clientId: "c3",
    status: "open",
    address: "3601 Fremont Ave N, Seattle, WA 98103",
    timeWindowStart: "11:00",
    timeWindowEnd: "13:00",
    driverId: null,
    contactName: null,
    contactPhone: null,
    deliveryNotes: null,
    dispatchNotes: null,
    lat: 47.6492,
    lng: -122.3499,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "RL-0088",
    clientId: "c4",
    status: "claimed",
    address: "9020 Rainier Ave S, Seattle, WA 98118",
    timeWindowStart: "14:00",
    timeWindowEnd: "16:00",
    driverId: "d2",
    contactName: "Eli Tran",
    contactPhone: "206-555-0374",
    deliveryNotes: "Signature required",
    dispatchNotes: null,
    lat: 47.5284,
    lng: -122.2693,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

let _orderSeq = 89;
export function nextOrderId(): string {
  return `RL-${String(_orderSeq++).padStart(4, "0")}`;
}
